force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Actual_Check_in__c.field-meta.xml
<CustomField>
    <fullName>Actual_Check_in__c</fullName>
    <label>Actual Check-in</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Check_in_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_in_Date__c</fullName>
    <label>Check-in Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Checked In</fullName>
            </value>
            <value>
                <fullName>Checked Out</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Is VIP Stay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NoShowUpdateBatch.cls
public class NoShowUpdateBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Check_in_Date__c, Actual_Check_in__c, Status__c
            FROM Reservation__c
            WHERE Check_in_Date__c  < TODAY          
            AND Status__c = 'Confirmed'            // status field = Confirmed
            AND Actual_Check_in__c = null          
        ]);
    }

    public void execute(Database.BatchableContext bc, List<Reservation__c> scope) {
        for ( Reservation__c r  : scope) {
            r.Status__c = 'No Show';            
        }
    for (Database.SaveResult sr : Database.update(scope, false)) {
    if (!sr.isSuccess()) {
        System.debug(sr.getErrors()[0].getMessage());
    }
}
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('No show sweep complete');
    }
}