force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Nightly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Nightly_Rate__c</fullName>
    <label>Nightly Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RoomRateAsync.cls
public class RoomRateAsync {

    @future
    public static void applyIncrease (List<Id> roomIds, Decimal pct) {
        List<Room__c> rooms = [SELECT Id, Nightly_Rate__c FROM Room__c WHERE Id IN :roomIds];

        for( Room__c r : rooms ) {
            if( r.Nightly_Rate__c != null){
                r.Nightly_Rate__c = r.Nightly_Rate__c * ( 1 + (pct/100));
        }
       
    }
        update rooms;
    }

    @future
    public static void secondFuture() {
        System.debug('second future ran');
    }


}